raw_data_path: "DATA/T1.csv"

transformation:
  train_size: 0.8
  val_size: 0.1
  test_size: 0.1
  window_size: 10
  preprocessor_file_path: "artifacts/preprocessor.pkl"
  test_data_path: "DATA/test.csv"


model:
  model_save_path: "artifacts/trained_model.keras"
  epochs: 10
  batch_size: 32
  